### ISSUE TITLE
AU Linux kernel autumn 2017 запрос на проверку mutex Кольцов Михаил

### ISSUE THREAD

**Issue by ItsLastDay** [ItsLastDay/au-linux-kernel-autumn-2017#5]
c515de952e151b9d611a2e2b6d8675473576cb9a

Tests do not pass, so I don't expect 100% for this task.

**Comment by eabatalov** [comment]
Well. There are some not completed features that simplify the solution a lot. Also there are some serious mistakes (unfortunately). But I hope that the exercise was useful. I can give maximum 45% for the task.
